// <auto-generated />
using System;
using EasyCarpet.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EasyCarpet.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210513121432_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EasyCarpet.Domain.Models.Carpet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SquareYardPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Carpet");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9cf37a50-a08f-4ed6-9505-2cb18af43605"),
                            Brand = "Traffic Master",
                            CreatedDate = new DateTime(2021, 5, 13, 8, 14, 32, 68, DateTimeKind.Local).AddTicks(571),
                            Description = "Medium Beige / Dark Beige flecks, indoor residential",
                            Image = "TrafficMasterBrown.jpg",
                            Length = 200m,
                            ModifiedDate = new DateTime(2021, 5, 13, 8, 14, 32, 70, DateTimeKind.Local).AddTicks(6417),
                            Name = "TrafficMaster: Brown",
                            SquareYardPrice = 5.89m,
                            Style = "Plush",
                            Width = 12m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
